### ISSUE TITLE
Waffle crashes when URL has no path

### ISSUE THREAD

**Issue by woylie** [elixir-waffle/waffle#106]
If a URL is passed to Waffle (e.g. through `cast_attachments`), and the URL has no path (e.g. `https://google.com`), Waffle causes an exception, because it passes the path of the parsed URI to `Path.basename/1` without checking for `nil` first. 

https://github.com/elixir-waffle/waffle/blob/master/lib/waffle/file.ex#L17

```
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
    (elixir 1.14.2) IO.chardata_to_string(nil)
    (elixir 1.14.2) lib/path.ex:383: Path.basename/1
    (waffle 1.1.6) lib/waffle/file.ex:18: Waffle.File.new/2
    (waffle 1.1.6) lib/waffle/actions/store.ex:54: Waffle.Actions.Store.store/2
    (waffle_ecto 0.0.11) lib/waffle_ecto/type.ex:21: Waffle.Ecto.Type.cast/2
```

Waffle should handle this case gracefully.

**Comment by woylie** [comment]
> @woylie would this issue also cover URLs with a non-traditional "filename" such as `https://google.com/test/.jpg` ? I have encountered a service that provides URLs in this form, and I suspect that I will need to refactor some of the filename handling code in waffle to deal with that case.

I linked the relevant code. If you run it with a URL in that format, you get:

```elixir
iex> URI.parse("https://google.com/test/.jpg").path |> Path.basename() |> URI.decode()
".jpg"
```

So it doesn't crash at least.
