### ISSUE TITLE
How to create single frame gif preview?

### ISSUE THREAD

**Issue by Zchandev** [elixir-waffle/waffle#68]
Hello. I use Elixir 1.10.3 and Waffle 1.1.3.

I have this code to transform JPG and it works fine:

```
  def transform(:thumb, _) do
    {:convert, "-thumbnail 300x300^ -gravity center -extent 300x300 -format jpg", :jpg}
  end
```

But when I upload gifs, I receive this error:
```
[warn] file = %Waffle.File{binary: nil, file_name: "1602417234419.gif", is_tempfile?: true, path: "/var/folders/fv/yj6hf4q52cq17v_qh19q6gt80000gn/T/32UDVLQVHE7HGG35CUUXT2M2KN6CAHMR.jpg"}
[error] Task #PID<0.667.0> started from #PID<0.679.0> terminating
** (File.CopyError) could not copy from "/var/folders/fv/yj6hf4q52cq17v_qh19q6gt80000gn/T/32UDVLQVHE7HGG35CUUXT2M2KN6CAHMR.jpg" to "src/183/1602417234419s.jpg": no such file or directory
    (elixir 1.10.3) lib/file.ex:709: File.copy!/3
    (waffle 1.1.3) lib/waffle/storage/local.ex:38: Waffle.Storage.Local.put/3
    (waffle 1.1.3) lib/waffle/actions/store.ex:130: Waffle.Actions.Store.put_version/3
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<1.8149634/0 in Waffle.Actions.Store.async_put_version/3>
    Args: []
[error] Ranch protocol #PID<0.667.0> of listener ZchanWeb.Endpoint.HTTP (connection #PID<0.666.0>, stream id 1) terminated
** (exit) %File.CopyError{action: "copy", destination: "src/183/1602417234419s.jpg", on: "", reason: :enoent, source: "/var/folders/fv/yj6hf4q52cq17v_qh19q6gt80000gn/T/32UDVLQVHE7HGG35CUUXT2M2KN6CAHMR.jpg"}
    (elixir 1.10.3) lib/file.ex:709: File.copy!/3
    (waffle 1.1.3) lib/waffle/storage/local.ex:38: Waffle.Storage.Local.put/3
    (waffle 1.1.3) lib/waffle/actions/store.ex:130: Waffle.Actions.Store.put_version/3
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3

r
** (CompileError) iex:1: undefined function r/0
```

I have found that I can take the first frame by using 'example.gif[0]' as filename.  Is there a way to use it in Waffle?

**Comment by achempion** [comment]
It looks like your rule is only for files with `jpg` extension.

**Comment by Zchandev** [comment]
> It looks like your rule is only for files with `jpg` extension.

Thanks. I have changed my code to:
```
 {:convert, "-thumbnail 300x300^ -gravity center -extent 300x300 -format jpg", :gif}
```

However, it only creates new resized gif file instead of single frame jpg

**Comment by achempion** [comment]
I think it's because your transformation rule describes resizing, not
slicing.

If you have a working example for slicing we could publish it to the
documentation.

**Comment by Zchandev** [comment]
> I think it's because your transformation rule describes resizing, not slicing. If you have a working example for slicing we could publish it to the documentation.

I have tried in console:
```
magick convert -thumbnail 300x300 -gravity center -extent 300x300 -format jpg 'example.gif[0]' frame.jpg
```

It works, but I have to specify another file name. How can I do it in Waffle? Looks like there is no argument for that

**Comment by achempion** [comment]
We have your example [covered in documentation](https://hexdocs.pm/waffle/Waffle.Processor.html)

```elixir
# Take the first frame of a gif and process it into a square jpg:
{:convert, fn(input, output) -> "#{input}[0] -strip -thumbnail 100x100^ -gravity center -extent 100x100 -format jpg #{output}", :jpg}
```
